# Simple location code-to-label lookup table

BC:  Bibliographic Control
BT:  Butler Preservation
CI:  Interlibrary Loan
# CV:  Milstein Reserves
CV:  Butler Library
MP:  Monographic Recon -- for MRP
# LIBSYS-1647 - Create new Offsite delivery location
# MZ:  ReCAP Coordinator
MZ:  Reid Hall (Paris, France)
IL:  ReCAP Interlibrary Loan
AR:  Avery Library
BL:  Barnard Library
UT:  Burke Library (UTS)
BS:  Business/Econ Library
BU:  Butler Library
EA:  East Asian Library
EN:  Engineering Library
GS:  Lamont-Doherty Earth Observatory
HS:  Health Sciences Library
CJ:  Journalism Library
LE:  Lehman Library
RH:  Lehman Suite
ML:  Mathematics Library
CF:  401 Butler Library (Microform Reading Room)
MR:  Music & Arts Library
RS:  Rare Book Library
CA:  Science & Engineering Lib (NWC Building)
SW:  Social Work Library


offsite_locations:
  # location codes for the two ReCAP partners
  - scsbnypl
  - scsbpul
  # (hyphens are old pattern - no longer used?)
  - scsb-nypl
  - scsb-pul
  # Columbia's Voyager offsite location codes
  #   N.B., this list does NOT include ALL Voyager offsite location codes.
  #   For example, RBML offsite (off,rbx) is not directly requestable by patrons.
  - off,ave
  - off,bio
  - off,bmc
  - off,bssc
  - off,bus
  - off,che
  - off,docs
  - off,eal
  - off,ean
  - off,eax
  - off,eng
  - off,fax
  - off,glg
  - off,glx
  - off,gsc
  - off,hsl
  - off,hsr
  - off,jou
  - off,leh
  - off,les
  - off,mat
  - off,mrr
  - off,msc
  - off,msr
  - off,mus
  - off,mvr
  - off,phy
  - off,psy
  - off,ref
  - off,sci
  - off,sls
  - off,swx
  - off,unr
  - off,utmrl
  - off,utn
  - off,utp
  - off,uts
  - off,war


